import streamlit as st
import torch
import re
from transformers import GPT2LMHeadModel, GPT2TokenizerFast
from collections import OrderedDict

# Define the model class (moved from your Flask app)
class GPT2PPL:
    def __init__(self, model_id="gpt2"):
        self.model_id = model_id
        self.model = GPT2LMHeadModel.from_pretrained(model_id)
        self.tokenizer = GPT2TokenizerFast.from_pretrained(model_id)
        self.max_length = self.model.config.n_positions
        self.stride = 512

    def getResults(self, threshold):
        if threshold < 60:
            label = 0
            return "The Text is generated by AI.", label
        elif threshold < 80:
            label = 0
            return "The Text most probably contains parts which are generated by AI. (requires more text for better judgment)", label
        else:
            label = 1
            return "The Text is written by a Human.", label

    def __call__(self, sentence):
        results = OrderedDict()
        total_valid_char = re.findall("[a-zA-Z0-9]+", sentence)
        total_valid_char = sum([len(x) for x in total_valid_char])  # finds len of all the valid characters in a sentence
        if total_valid_char < 100:
            return {"status": "Please input more text (minimum 100 characters)"}, "Please input more text (minimum 100 characters)"
        
        lines = re.split(r'(?<=[.?!][ \[\(])|(?<=\n)\s*', sentence)
        lines = list(filter(lambda x: (x is not None) and (len(x) > 0), lines))
        ppl = self.getPPL(sentence)
        results["Perplexity"] = ppl

        Perplexity_per_line = []
        for line in lines:
            if re.search("[a-zA-Z0-9]+", line) is None:
                continue
            ppl = self.getPPL(line)
            Perplexity_per_line.append(ppl)

        results["Perplexity per line"] = sum(Perplexity_per_line) / len(Perplexity_per_line)
        results["Burstiness"] = max(Perplexity_per_line)
        out, label = self.getResults(results["Perplexity per line"])
        results["label"] = label
        return results, out

    def getPPL(self, sentence):
        encodings = self.tokenizer(sentence, return_tensors="pt")
        seq_len = encodings.input_ids.size(1)
        nlls = []
        prev_end_loc = 0

        for begin_loc in range(0, seq_len, self.stride):
            end_loc = min(begin_loc + self.max_length, seq_len)
            trg_len = end_loc - prev_end_loc
            input_ids = encodings.input_ids[:, begin_loc:end_loc]
            target_ids = input_ids.clone()
            target_ids[:, :-trg_len] = -100

            with torch.no_grad():
                outputs = self.model(input_ids, labels=target_ids)
                neg_log_likelihood = outputs.loss * trg_len

            nlls.append(neg_log_likelihood)
            prev_end_loc = end_loc
            if end_loc == seq_len:
                break

        ppl = int(torch.exp(torch.stack(nlls).sum() / end_loc))
        return ppl

# ==========================================
# STREAMLIT UI
# ==========================================

# Configure the page
st.set_page_config(
    page_title="Generative AI Detection",
    page_icon="🤖",
    layout="centered"
)

# Cache the model so it doesn't reload on every interaction
@st.cache_resource
def load_model():
    return GPT2PPL()

# Try loading the model, with a spinner
with st.spinner("Loading AI model (this may take a moment on startup)..."):
    try:
        gpt2ppl = load_model()
        model_loaded = True
    except Exception as e:
        st.error(f"Failed to load the model: {e}")
        model_loaded = False

# Title and description
st.title("🤖 Generative AI Detection")
st.markdown("""
Detect if text was written by a human or generated by an AI model (like ChatGPT).
The tool calculates **Perplexity** and **Burstiness** using GPT-2 to make a prediction.
""")

st.divider()

# Input area
user_input = st.text_area(
    "Enter the text you want to analyze:", 
    height=250, 
    placeholder="Paste your text here. Minimum 100 characters required for accurate results..."
)

# Analyze button
if st.button("Analyze Text", type="primary", use_container_width=True):
    if not model_loaded:
        st.error("The model failed to load. Please try refreshing the page.")
    elif len(user_input.strip()) == 0:
        st.warning("Please enter some text to analyze.")
    else:
        with st.spinner("Analyzing text..."):
            try:
                results, output_msg = gpt2ppl(user_input)
                
                if "status" in results and "minimum 100 characters" in results["status"]:
                    st.warning(results["status"])
                else:
                    # Display Results
                    st.divider()
                    st.subheader("Results")
                    
                    # Highlight the main outcome
                    if results.get("label") == 0:
                        st.error(f"⚠️ {output_msg}")
                    else:
                        st.success(f"✅ {output_msg}")
                    
                    # Display detailed metrics
                    st.markdown("### Detailed Metrics")
                    col1, col2, col3 = st.columns(3)
                    
                    col1.metric("Perplexity", f"{results.get('Perplexity', 0):.2f}")
                    col2.metric("Perplexity per line", f"{results.get('Perplexity per line', 0):.2f}")
                    col3.metric("Burstiness", f"{results.get('Burstiness', 0):.2f}")
                    
            except Exception as e:
                st.error(f"An error occurred during analysis: {e}")

st.markdown("---")
st.caption("Powered by Streamlit, PyTorch, and Transformers.")
